model:
  name: PatchCore
  backbone: wide_resnet50_2
  layers:
    - layer2
    - layer3
    - layer4
  pre_trained: true
  coreset_sampling_ratio: 0.12
  num_neighbors: 9

dataset:
  path: dataset/fabric_tunus
  name: fabric_tunus
  task: segmentation
  format: folder
  normal_dir: train/good/
  abnormal_dir: test/defect/
  image_size: 224
  train_batch_size: 32
  test_batch_size: 32
  num_workers: 2
  plt_output_path: dataset/outputs/fabric_tunus/
  image_out_path: dataset/fabric_tunus/outputs1/

engine:
  max_epochs: 50
  callbacks:
    - early_stopping:
        monitor: image_AUROC
        mode: max
        patience: 5
    - model_checkpoint:
        mode: max
        monitor: image_AUROC
        save_last: true
        auto_insert_metric_name: true
        every_n_epochs: 1
  normalization: Z_SCORE
  threshold: F1AdaptiveThreshold
  task: classification 
  image_metrics:
    - accuracy
    - precision
  pixel_metrics:
    - IoU
    - precision
  default_root_dir: results
  logger: TensorBoardLogger
  accelerator: auto
  devices: 1
